#!/usr/bin/env python3
"""
FreeCAD Macro Installer for brick_generator

This file is auto-generated by the git deployment system.
It provides a FreeCAD-native way to install the brick generator.

Usage in FreeCAD:
1. Open the Macro menu
2. Select "Execute macro..."
3. Choose this file (freecad_installer.py)
4. Run it

Version: 4.2.0
"""

import os
import sys
import shutil
from pathlib import Path

GENERATOR_VERSION = "4.2.0"

def run():
    """Install brick generator when executed as FreeCAD macro."""
    try:
        import FreeCAD
        freecad_available = True
    except ImportError:
        freecad_available = False
    
    if freecad_available:
        # We're running inside FreeCAD
        macro_dir = Path(FreeCAD.getUserMacroDir())
    else:
        # Fall back to platform detection
        import platform
        system = platform.system()
        
        if system == "Darwin":  # macOS
            base_dir = Path.home() / "Library" / "Application Support" / "FreeCAD"
        elif system == "Windows":
            base_dir = Path.home() / "AppData" / "Roaming" / "FreeCAD"
        else:  # Linux
            base_dir = Path.home() / ".config" / "FreeCAD"
        
        macro_dir = base_dir / "Macro"
    
    if not macro_dir.exists():
        print(f"ERROR: FreeCAD macro directory not found: {macro_dir}")
        return False
    
    # Get source directory (where this installer is)
    script_dir = Path(__file__).parent
    
    # Create brick subdirectory for library
    brick_dir = macro_dir / "brick"
    brick_dir.mkdir(parents=True, exist_ok=True)
    
    # Copy files
    try:
        # Copy macro to ROOT (so it appears in FreeCAD UI)
        macro_src = script_dir / "brick_generator_macro.FCMacro"
        macro_dst = macro_dir / "brick_generator_macro.FCMacro"
        if macro_src.exists():
            shutil.copy2(macro_src, macro_dst)
        
        # Copy geometry library to brick/ subdirectory
        geom_src = script_dir / "brick_geometry.py"
        geom_dst = brick_dir / "brick_geometry.py"
        
        if geom_src.exists():
            shutil.copy2(geom_src, geom_dst)
        
        print(f"✓ Brick generator v{GENERATOR_VERSION} installed")
        print(f"  Location: {macro_dir}")
        print(f"  Macro: brick_generator_macro.FCMacro")
        print(f"  Library: brick/brick_geometry.py")
        return True
        
    except Exception as e:
        print(f"ERROR: Installation failed: {e}")
        return False


if __name__ == "__main__":
    success = run()
    sys.exit(0 if success else 1)
